backend:
  name: gitea
  repo: beardedtek/flowbite-beardedtek.com
  branch: main
  app_id: ca91733b-543f-4506-b2cc-7c6120d20b57
  base_url: https://git.beardedtek.com
  api_root: https://git.beardedtek.com/api/v1
  auth_endpoint: https://git.beardedtek.com/login/oauth/authorize
  commit_messages:
    create: 'content: create {{collection}} "{{slug}}"'
    update: 'content: update {{collection}} "{{slug}}"'
    delete: 'content: delete {{collection}} "{{slug}}"'
    uploadMedia: 'media: upload {{path}}'
    deleteMedia: 'media: delete {{path}}'

media_folder: "static/images/uploads"
public_folder: "/images/uploads"